### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by ghost** [TheJoyfulProgrammer/The-Gallows---Dead-Mans-Curse#1]
This program won't compile on my Linux system.

**Comment by TheJoyfulProgrammer** [comment]
> This program won't compile on my Linux system.

The Gallows - Dead Man's Curse is only designed for Windows and will not compile in Linux. It currently uses the Windows Console API to do all the magic. At this point, I am not sure I will ever modify it to run in Linux as well. 

On a side note, the Window's console and the Linux Terminal are two different emulators and have different methods of doing things. Of course, I could use the NCurses library to make it work in Windows and Linux, but that is for another time, if ever.
